//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginControlTester.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginControlTester.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        internal static string AUTO_LOGIN {
            get {
                return ResourceManager.GetString("AUTO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - from Parent MainWindow. Just to indicate that at this point the parent decides the next course of Action..
        /// </summary>
        internal static string CONNECTED_FROM_PARENT_MAIN_WINDOW {
            get {
                return ResourceManager.GetString("CONNECTED_FROM_PARENT_MAIN_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected - Login Experience. Just to indicate that at this point the parent decides the next course of Action..
        /// </summary>
        internal static string CONNECTED_LOGIN_EXPERIENCE {
            get {
                return ResourceManager.GetString("CONNECTED_LOGIN_EXPERIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials already saved in configuration\nChoose Yes to Auto Login or No to Reset Credentials.
        /// </summary>
        internal static string CREDENTIALS_ALREADY_SAVED_IN_CONFIGURATION {
            get {
                return ResourceManager.GetString("CREDENTIALS_ALREADY_SAVED_IN_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - This is the display name of account entity in the Org. Means Parent is able to Query the Org..
        /// </summary>
        internal static string DISPLAY_NAME_ENTITY {
            get {
                return ResourceManager.GetString("DISPLAY_NAME_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Login with cached credentials..
        /// </summary>
        internal static string FAILED_TO_LOGIN {
            get {
                return ResourceManager.GetString("FAILED_TO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        internal static string LOGIN_FAILURE {
            get {
                return ResourceManager.GetString("LOGIN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from ConnectionManager.
        /// </summary>
        internal static string NOTIFICATION_FROM_CONNECTION_MANAGER {
            get {
                return ResourceManager.GetString("NOTIFICATION_FROM_CONNECTION_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from Parent.
        /// </summary>
        internal static string NOTIFICATION_FROM_PARENT {
            get {
                return ResourceManager.GetString("NOTIFICATION_FROM_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Login to CRM using cached credentials.
        /// </summary>
        internal static string UNABLE_TO_LOGIN_TO_CRM {
            get {
                return ResourceManager.GetString("UNABLE_TO_LOGIN_TO_CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Login to CRM using cached credentials. Org Not found.
        /// </summary>
        internal static string UNABLE_TO_LOGIN_TO_CRM_ORGANIZATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("UNABLE_TO_LOGIN_TO_CRM_ORGANIZATION_NOT_FOUND", resourceCulture);
            }
        }
    }
}
