//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseClient_Core_UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataverseClient_Core_UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{
        ///    &quot;@odata.context&quot;: &quot;{0}/api/data/v9.1/$metadata#Microsoft.Dynamics.CRM.RetrieveCurrentOrganizationResponse&quot;,
        ///    &quot;Detail&quot;: {{
        ///        &quot;OrganizationId&quot;: &quot;{1}&quot;,
        ///        &quot;FriendlyName&quot;: &quot;{2}&quot;,
        ///        &quot;OrganizationVersion&quot;: &quot;{3}&quot;,
        ///        &quot;EnvironmentId&quot;: &quot;{4}&quot;,
        ///        &quot;DatacenterId&quot;: &quot;{5}&quot;,
        ///        &quot;Geo&quot;: &quot;{6}&quot;,
        ///        &quot;TenantId&quot;: &quot;{7}&quot;,
        ///        &quot;UrlName&quot;: &quot;{8}&quot;,
        ///        &quot;UniqueName&quot;: &quot;{9}&quot;,
        ///        &quot;State&quot;: &quot;{10}&quot;,
        ///        &quot;Endpoints&quot;: {{
        ///            &quot;Count&quot;: 3,
        ///            &quot;IsReadOnly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveCurrentOrg {
            get {
                return ResourceManager.GetString("RetrieveCurrentOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {{   &quot;@odata.context&quot;: &quot;https://{0}.crm.dynamics.com/api/data/v9.1/$metadata#Microsoft.Dynamics.CRM.WhoAmIResponse&quot;,
        ///    &quot;BusinessUnitId&quot;: &quot;{1}&quot;,
        ///    &quot;UserId&quot;: &quot;{2}&quot;,
        ///    &quot;OrganizationId&quot;: &quot;{3}&quot;}}
        ///.
        /// </summary>
        internal static string WhoAmIResponse {
            get {
                return ResourceManager.GetString("WhoAmIResponse", resourceCulture);
            }
        }
    }
}
