//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("Microsoft Common Data Service Application API Wrapper")]
[assembly: AssemblyDescription("Microsoft CDS API helper library. Provides authentication support, telemetry and helpers to work with CDS API's")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Microsoft Common Data Service")]
[assembly: AssemblyVersion("0.0.1.0")]
[assembly: AssemblyFileVersion("0.0.1.1")]
[assembly: AssemblyInformationalVersion("0.0.1.1+gc00bfa0")]
[assembly: AssemblyCopyright("© 2019 Microsoft Corporation. All rights reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

