//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerPlatform.Dataverse.ConnectControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerPlatform.Dataverse.ConnectControl.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error requesting orgs from the discovery server.
        /// </summary>
        internal static string CRMCONNECT_ERR_ACCESS {
            get {
                return ResourceManager.GetString("CRMCONNECT_ERR_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User attention required.
        /// </summary>
        internal static string CRMCONNECT_ERR_MULTIORG {
            get {
                return ResourceManager.GetString("CRMCONNECT_ERR_MULTIORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Status Event.
        /// </summary>
        internal static string CRMCONNECT_ERR_UNEXPECTED_STATUS {
            get {
                return ResourceManager.GetString("CRMCONNECT_ERR_UNEXPECTED_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Live Registration file. Wait a few minutes and try again..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_FAILED_TO_GENERATE_LIVE_DEVICEFILE {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_FAILED_TO_GENERATE_LIVE_DEVICEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access any of the organizations in the Microsoft Common Data Service region that you specified. If you&apos;re not sure which region your organization resides in, choose &quot;Don&apos;t know&quot; for the CDS region and try again. Otherwise check with your CDS administrator..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_NO_ORGS_FOUND_ONLINE {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_NO_ORGS_FOUND_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access any of the organizations on the Microsoft Dynamics CRM server that you specified. Check with your CRM administrator..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_NO_ORGS_FOUND_PREM {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_NO_ORGS_FOUND_PREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the Microsoft Common Data Service....
        /// </summary>
        internal static string CRMCONNECT_LOGIN_PROCESS_CONNECT_TO_UII {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_PROCESS_CONNECT_TO_UII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating connection to Microsoft Common Data Service....
        /// </summary>
        internal static string CRMCONNECT_LOGIN_PROCESS_CONNNECTING {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_PROCESS_CONNNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving organizations from Microsoft Common Data Service....
        /// </summary>
        internal static string CRMCONNECT_LOGIN_PROCESS_GET_ORGS {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_PROCESS_GET_ORGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving organizations from Microsoft Common Data Service - {0}....
        /// </summary>
        internal static string CRMCONNECT_LOGIN_PROCESS_GET_ORGS_LIVE {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_PROCESS_GET_ORGS_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing connections to Microsoft Common Data Service....
        /// </summary>
        internal static string CRMCONNECT_LOGIN_PROCESS_INIT_UII_CONNECTION {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_PROCESS_INIT_UII_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string CRMCONNECT_LOGIN_PROCESS_WAIT_TEXT {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_PROCESS_WAIT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to Microsoft Common Data Service - {0}..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_UNABLE_TO_CONNECT_GENERAL {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_UNABLE_TO_CONNECT_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication type must be specified..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_AUTHTYPE {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_AUTHTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the authentication type..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_AUTHTYPE_MSG {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_AUTHTYPE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Logon type and credentials aren&apos;t valid.
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_LOGINTYPE {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_LOGINTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default credentials can be used only for Active Directory and IFD. Select an appropriate authentication type or provide user credentials..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_LOGINTYPE_INCOMPATIBLE_LOGIN_TYPE {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_LOGINTYPE_INCOMPATIBLE_LOGIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_PASSWORD {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a password..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_PASSWORD_MSG {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_PASSWORD_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CDS server name is required..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_SERVER {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a CDS server to connect to..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_SERVER_MSG {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_SERVER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name is required..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_USERID {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a user name..
        /// </summary>
        internal static string CRMCONNECT_LOGIN_VALIDATION_ERR_USERID_MSG {
            get {
                return ResourceManager.GetString("CRMCONNECT_LOGIN_VALIDATION_ERR_USERID_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren’t authorized to use the application. Contact your administrator to get access..
        /// </summary>
        internal static string CRMCONNECT_MSG_EMPTY_LOGIN_DETAILS {
            get {
                return ResourceManager.GetString("CRMCONNECT_MSG_EMPTY_LOGIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security settings aren’t configured correctly. Contact your administrator to update your security settings..
        /// </summary>
        internal static string CRMCONNECT_MSG_INVALID_LOGIN_DETAILS {
            get {
                return ResourceManager.GetString("CRMCONNECT_MSG_INVALID_LOGIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security settings aren’t configured correctly. Contact your administrator to update your security settings.\n{0}.
        /// </summary>
        internal static string CRMCONNECT_MSG_INVALID_LOGIN_DETAILS_PARAMS {
            get {
                return ResourceManager.GetString("CRMCONNECT_MSG_INVALID_LOGIN_DETAILS_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while logging on to the server. Please try again later..
        /// </summary>
        internal static string CRMCONNECT_MSG_LOGIN_FAILURE {
            get {
                return ResourceManager.GetString("CRMCONNECT_MSG_LOGIN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to logon - The client isn&apos;t configured correctly. Contact your CDS administrator..
        /// </summary>
        internal static string CRMCONNECT_MSG_WEBSERVICE_CLIENT_MISCONFIGURED {
            get {
                return ResourceManager.GetString("CRMCONNECT_MSG_WEBSERVICE_CLIENT_MISCONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a CDS Enviroment to continue.
        /// </summary>
        internal static string CRMCONNECT_NOORG_SEL {
            get {
                return ResourceManager.GetString("CRMCONNECT_NOORG_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name is not valid..
        /// </summary>
        internal static string CRMCONNECT_PROFILENAME_INVALID {
            get {
                return ResourceManager.GetString("CRMCONNECT_PROFILENAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Microsoft Common Data Service Complete.
        /// </summary>
        internal static string CRMCONNECT_SERVER_CONNECT_GOOD {
            get {
                return ResourceManager.GetString("CRMCONNECT_SERVER_CONNECT_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataverse Login Control.
        /// </summary>
        internal static string SERVER_LOGINCONTROL_LOCALIZEDCONTROLTYPE {
            get {
                return ResourceManager.GetString("SERVER_LOGINCONTROL_LOCALIZEDCONTROLTYPE", resourceCulture);
            }
        }
    }
}
