//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerPlatform.Dataverse.ConnectControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerPlatform.Dataverse.ConnectControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details.
        /// </summary>
        public static string ERROR_DETAILS {
            get {
                return ResourceManager.GetString("ERROR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to CDS. Verify the server name and logon credentials. See the log file for details..
        /// </summary>
        public static string ERROR_LOGIN_REQUEST {
            get {
                return ResourceManager.GetString("ERROR_LOGIN_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string INSTANCEURLCAPTURE_OKBTN {
            get {
                return ResourceManager.GetString("INSTANCEURLCAPTURE_OKBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter organization instance url.
        /// </summary>
        public static string INSTANCEURLCAPTURE_TITLE {
            get {
                return ResourceManager.GetString("INSTANCEURLCAPTURE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url entered is invalid or not formated correctly.
        /// </summary>
        public static string INSTANCEURLCAPTURE_URL_Error {
            get {
                return ResourceManager.GetString("INSTANCEURLCAPTURE_URL_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: https://orgname.crm.dynamics.com.
        /// </summary>
        public static string INSTANCEURLCAPTURE_URL_Example {
            get {
                return ResourceManager.GetString("INSTANCEURLCAPTURE_URL_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance url:.
        /// </summary>
        public static string INSTANCEURLCAPTURE_URL_LABLE {
            get {
                return ResourceManager.GetString("INSTANCEURLCAPTURE_URL_LABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced.
        /// </summary>
        public static string LOGIN_FRM_ADVANCED {
            get {
                return ResourceManager.GetString("LOGIN_FRM_ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of available organizations.
        /// </summary>
        public static string LOGIN_FRM_ASK_FOR_ORG {
            get {
                return ResourceManager.GetString("LOGIN_FRM_ASK_FOR_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string LOGIN_FRM_AUTHTYPE_AD {
            get {
                return ResourceManager.GetString("LOGIN_FRM_AUTHTYPE_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeRealmsStore.xml.
        /// </summary>
        public static string LOGIN_FRM_AUTHTYPE_CONFIG_FILE_NAME {
            get {
                return ResourceManager.GetString("LOGIN_FRM_AUTHTYPE_CONFIG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet-facing deployment(IFD).
        /// </summary>
        public static string LOGIN_FRM_AUTHTYPE_IFD {
            get {
                return ResourceManager.GetString("LOGIN_FRM_AUTHTYPE_IFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth.
        /// </summary>
        public static string LOGIN_FRM_AUTHTYPE_OAUTH {
            get {
                return ResourceManager.GetString("LOGIN_FRM_AUTHTYPE_OAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string LOGIN_FRM_CANCEL_BTN {
            get {
                return ResourceManager.GetString("LOGIN_FRM_CANCEL_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string LOGIN_FRM_CONNECTSTATUS {
            get {
                return ResourceManager.GetString("LOGIN_FRM_CONNECTSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Source:.
        /// </summary>
        public static string LOGIN_FRM_CRM_AUTH_SOURCE {
            get {
                return ResourceManager.GetString("LOGIN_FRM_CRM_AUTH_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-premises.
        /// </summary>
        public static string LOGIN_FRM_CRM_PREM_NAME {
            get {
                return ResourceManager.GetString("LOGIN_FRM_CRM_PREM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365.
        /// </summary>
        public static string LOGIN_FRM_DEPLOYMENT_O365 {
            get {
                return ResourceManager.GetString("LOGIN_FRM_DEPLOYMENT_O365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string LOGIN_FRM_DEPLOYMENT_ONLINE {
            get {
                return ResourceManager.GetString("LOGIN_FRM_DEPLOYMENT_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-premises.
        /// </summary>
        public static string LOGIN_FRM_DEPLOYMENT_PREM {
            get {
                return ResourceManager.GetString("LOGIN_FRM_DEPLOYMENT_PREM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Type:.
        /// </summary>
        public static string LOGIN_FRM_DEPLOYMENT_TYPE {
            get {
                return ResourceManager.GetString("LOGIN_FRM_DEPLOYMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string LOGIN_FRM_DOMAIN {
            get {
                return ResourceManager.GetString("LOGIN_FRM_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while processing the login request.  .
        /// </summary>
        public static string LOGIN_FRM_ERR_FIRST {
            get {
                return ResourceManager.GetString("LOGIN_FRM_ERR_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Error Log.
        /// </summary>
        public static string LOGIN_FRM_ERR_SECOND {
            get {
                return ResourceManager.GetString("LOGIN_FRM_ERR_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string LOGIN_FRM_GB_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_FRM_GB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Desktop Logon.
        /// </summary>
        public static string LOGIN_FRM_GROUP_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_FRM_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Login.
        /// </summary>
        public static string LOGIN_FRM_LOGIN_BTN {
            get {
                return ResourceManager.GetString("LOGIN_FRM_LOGIN_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_FRM_LOGIN_LBL {
            get {
                return ResourceManager.GetString("LOGIN_FRM_LOGIN_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple CDS Organizations are available to you. Please choose the CDS Organization you would like to connect to..
        /// </summary>
        public static string LOGIN_FRM_MULT_ORG {
            get {
                return ResourceManager.GetString("LOGIN_FRM_MULT_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Region.
        /// </summary>
        public static string LOGIN_FRM_ONLINE_REGION {
            get {
                return ResourceManager.GetString("LOGIN_FRM_ONLINE_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string LOGIN_FRM_ORG_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_FRM_ORG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_FRM_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_FRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Region.
        /// </summary>
        public static string LOGIN_FRM_REG_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_FRM_REG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Organizations from CDS.
        /// </summary>
        public static string LOGIN_FRM_RETRIEVE {
            get {
                return ResourceManager.GetString("LOGIN_FRM_RETRIEVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to Default Organization ({0}).
        /// </summary>
        public static string LOGIN_FRM_RETRIEVE_DEF {
            get {
                return ResourceManager.GetString("LOGIN_FRM_RETRIEVE_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string LOGIN_FRM_SERVERNAME {
            get {
                return ResourceManager.GetString("LOGIN_FRM_SERVERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Organization.
        /// </summary>
        public static string LOGIN_FRM_SERVERORG {
            get {
                return ResourceManager.GetString("LOGIN_FRM_SERVERORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string LOGIN_FRM_SERVERPORT {
            get {
                return ResourceManager.GetString("LOGIN_FRM_SERVERPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDS Login.
        /// </summary>
        public static string LOGIN_FRM_TITLE {
            get {
                return ResourceManager.GetString("LOGIN_FRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in as current user.
        /// </summary>
        public static string LOGIN_FRM_USE_DEF_CREDS {
            get {
                return ResourceManager.GetString("LOGIN_FRM_USE_DEF_CREDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string LOGIN_FRM_USE_SSL {
            get {
                return ResourceManager.GetString("LOGIN_FRM_USE_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LOGIN_FRM_USERNAME {
            get {
                return ResourceManager.GetString("LOGIN_FRM_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Window.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
