#
# Module manifest for module 'Microsoft.PowerPlatform.Dataverse.Client.PowerShell'
#
# Generated by: Microsoft Power Platform Team
#

@{

  # Script module or binary module file associated with this manifest.
  RootModule           = 'Microsoft.PowerPlatform.Dataverse.Client.PowerShell.psm1'

  # Version number of this module.
  ModuleVersion        = '1.1.0.0'

  # ID used to uniquely identify this module
  GUID                 = '996701E3-B7C8-4A91-AC14-BB27918350DA'

  # Author of this module
  Author               = 'Microsoft Power Platform Team'

  # Company or vendor of this module
  CompanyName          = 'Microsoft'

  # Copyright statement for this module
  Copyright            = 'Copyright 2023. All rights reserved.'

  # Description of the functionality provided by this module
  Description          = 'PowerShell Module for Connecting to Power Platform Dataverse'

  # Minimum version of the Windows PowerShell engine required by this module
  PowerShellVersion    = '7.0'

  # Supported PSEditions: 'Desktop', 'Core'
  CompatiblePSEditions = @('Core')

  # Modules that must be imported into the global environment prior to importing this module
  #RequiredModules = 

  # Assemblies that must be loaded prior to importing this module
  RequiredAssemblies   = @(
      'Microsoft.PowerPlatform.Dataverse.Client.dll',
      'Microsoft.PowerPlatform.Dataverse.Client.PowerShell.dll',
      'Microsoft.Xrm.Sdk.dll',
      'Microsoft.Crm.Sdk.Proxy.dll',
      'Newtonsoft.Json.dll'
  )

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  NestedModules = if ($PSEdition -eq 'Core') {
    @(
      'Microsoft.PowerPlatform.Dataverse.Client.PowerShell.dll',
      'UtilityFunctions.psm1',
      'Microsoft.PowerPlatform.Dataverse.Client.Operations',
      'Microsoft.PowerPlatform.Dataverse.Client.Connect'
    )
  }
  else { # Desktop
    @(
        #null
    )
  }

  # Functions to export from this module
  FunctionsToExport    = @(
      'New-DataverseRecord',
      'Get-DataverseRecord',
      'Get-DataverseEntityMetadata',
      'Get-MyUserId',
      'Get-DataverseRecordsByFetch',
      'Get-DataverseOrgDbOrgSettings',
      'Get-DataverseEntityOptionSet',
      'Get-DataverseEntityAttributes',
      'Get-DataverseSystemSettings',
      'Set-DataverseRecord',
      'Set-DataverseSystemSettings',
      'Invoke-DataverseAction',
      'Remove-DataverseRecord',
      'Connect-PowerPlatformDataverse'
  )

  # Cmdlets to export from this module
  CmdletsToExport = @(
    'Get-PowerPlatformConnection'
  )

  # Variables to export from this module
  VariablesToExport = @(
  )

  # Aliases to export from this module
  AliasesToExport = @(
  )

  # List of all modules packaged with this module.
  ModuleList = @(
    'Microsoft.PowerPlatform.Dataverse.Client.PowerShell'
  )

  # List of all files packaged with this module
  #FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData          = @{

    PSData = @{

      # Tags applied to this module. These help with module discovery in online galleries.
      # Tags = @()

      # A URL to the license for this module.
      LicenseUri   = 'http://download.microsoft.com/download/E/1/8/E18C0FAD-FEC8-44CD-9A16-98EDC4DAC7A2/LicenseTerms.docx'

      # A URL to the main website for this project.
      ProjectUri   = 'https://github.com/microsoft/PowerPlatform-DataverseServiceClient'
      # A URL to an icon representing this module.
      IconUri      = 'https://connectoricons-prod.azureedge.net/powerappsforappmakers/icon_1.0.1056.1255.png'

      # ReleaseNotes of this module
      ReleaseNotes = '
Current Release:

>>CURRENTRELEASEID<<

'

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  #HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  #DefaultCommandPrefix = ''

}